#include <stdio.h>
#include <time.h>
#include <stdlib.h>
#include <malloc.h>
#include <sys/types.h>
#include <stdint.h>

uint64_t get_ticks()
{
	uint32_t low, high;
	asm( "rdtsc" : "=a" (low), "=d" (high));
	return (uint64_t)low | ((uint64_t)high << 32);
}

void main()
{
	uint64_t ticks_begin, ticks_end;
	double latentcy, throughout;
	ticks_begin = get_ticks();
	int i;
	for(i = 0; i < 100000; i++)
	{
		__asm{
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
			add eax, ebx
		}
	}
	ticks_end = get_ticks();
	latentcy = (double)(ticks_end - ticks_begin)/100000000;
	printf("latentcy: %f\n", latentcy);

	ticks_begin = get_ticks();

	for(i = 0; i < 100000; i++)
	{
		__asm{
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
			add ebx, eax
			add ecx, eax
			add edx, eax
			add esi, eax
			add edi, eax
		}
	}
	ticks_end = get_ticks();
	throughout = (double)(ticks_end - ticks_begin)/100000000;
	printf("throughout: %f\n", throughout);
	return;
}